/// Integration tests against pre-serialised domain JSON files.
///
/// JSON files live in `planner/test_domains/` and are generated by the full
/// pipeline (pandaPIparser → pandaPIgrounder → htn_parser.py).  Re-run
/// `domains/<name>/generate.py` and the pipeline to regenerate them if the
/// serialiser or domains change.
///
/// Expected probabilities are exact (closed-form):
///   prob_chain n steps, p=0.9  → 0.9^n
///   prob_method_select k methods → k/(k+1)
///   prob_retry k tokens, p=0.5 → 1 - 0.5^k
#[cfg(test)]
mod tests {
    use crate::domain_description::read_json_domain;
    use crate::search::{HeuristicType, SearchResult};
    use super::super::run;
    use super::super::TiebreakerKind;

    const TOLERANCE: f64 = 1e-4;

    fn check(json_path: &str, expected: f64) {
        let mut problem = read_json_domain(json_path);
        problem.rho = 0.0;
        let (result, _) = run(&problem, HeuristicType::HAdd, TiebreakerKind::Combined);
        match result {
            SearchResult::Success(policy) => {
                assert!(
                    (policy.success_probability - expected).abs() < TOLERANCE,
                    "{}: expected {:.6}, got {:.6}",
                    json_path, expected, policy.success_probability
                );
            }
            SearchResult::NoSolution => panic!("{}: expected success with prob {:.6}", json_path, expected),
        }
    }

    // ── prob_chain ────────────────────────────────────────────────────────────
    // N sequential steps, each p=0.9. Answer = 0.9^N.

    #[test]
    fn prob_chain_n03() {
        check("test_domains/prob_chain_n03.json", 0.9_f64.powi(3));
    }

    #[test]
    fn prob_chain_n05() {
        check("test_domains/prob_chain_n05.json", 0.9_f64.powi(5));
    }

    // ── prob_method_select ────────────────────────────────────────────────────
    // K methods with probabilities i/(K+1). Answer = K/(K+1).

    #[test]
    fn prob_method_select_k03() {
        check("test_domains/prob_method_select_k03.json", 3.0 / 4.0);
    }

    #[test]
    fn prob_method_select_k05() {
        check("test_domains/prob_method_select_k05.json", 5.0 / 6.0);
    }

    // ── prob_retry ────────────────────────────────────────────────────────────
    // K retry tokens, p=0.5 per attempt. Answer = 1 - 0.5^K.

    #[test]
    fn prob_retry_k03() {
        check("test_domains/prob_retry_k03.json", 1.0 - 0.5_f64.powi(3));
    }

    #[test]
    fn prob_retry_k05() {
        check("test_domains/prob_retry_k05.json", 1.0 - 0.5_f64.powi(5));
    }

    // ── prob_sequential_retry ─────────────────────────────────────────────────
    // N phases, R retries/phase (p=0.5 each). Answer = (1 − 0.5^R)^N.

    #[test]
    fn prob_sequential_retry_n2_r3() {
        check("test_domains/prob_sequential_retry_n02_r03.json",
              (1.0 - 0.5_f64.powi(3)).powi(2));
    }

    #[test]
    fn prob_sequential_retry_n3_r2() {
        check("test_domains/prob_sequential_retry_n03_r02.json",
              (1.0 - 0.5_f64.powi(2)).powi(3));
    }

    #[test]
    fn prob_sequential_retry_n3_r3() {
        check("test_domains/prob_sequential_retry_n03_r03.json",
              (1.0 - 0.5_f64.powi(3)).powi(3));
    }

    // ── prob_safe_vs_risky ────────────────────────────────────────────────────
    // N phases, R retry tokens. Answer = (1 − 0.15 × 0.4^(R−1))^N.
    // R=1 → planner prefers risky (0.85 > safe 0.6); no next token so m_safe_recurse inapplicable.
    // R=2 → planner prefers safe+recurse (0.94 > risky 0.85); strategy switch at R≥2.

    #[test]
    fn prob_safe_vs_risky_n3_r1() {
        check("test_domains/prob_safe_vs_risky_n03_r01.json",
              (1.0 - 0.15 * 0.4_f64.powi(0)).powi(3));  // 0.85^3
    }

    #[test]
    fn prob_safe_vs_risky_n2_r2() {
        check("test_domains/prob_safe_vs_risky_n02_r02.json",
              (1.0 - 0.15 * 0.4_f64.powi(1)).powi(2));  // 0.94^2
    }

    #[test]
    fn prob_safe_vs_risky_n3_r3() {
        check("test_domains/prob_safe_vs_risky_n03_r03.json",
              (1.0 - 0.15 * 0.4_f64.powi(2)).powi(3));  // ≈ 0.9297
    }

    #[test]
    fn prob_blocksworld_5() {
        check("test_domains/prob_blocksworld_5.json",
              0.996);
    }

}
